name: Restart Nginx on EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install SSH Key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Run Commands
        run: |
          cd /var/www/html/Portfolio
          sudo git status
          sudo git pull
          sudo nginx -t
          sudo systemctl restart nginx
          sudo systemctl status nginx
